bigfile: Terminate only current thread if loading-through-mmap from file fails
On usual kernel, if a file is mmaped, and then memory read, and
underlying file implementation return -EIO, the kernel sends SIGBUS to
client thread, and if that SIGBUS is not handled the whole client process
is terminated with coredump.

In bigfile/virtmem.c until now we were doing similar thing - if in
vma_on_pagefault() a read request to loadblk() fails - we abort the
whole process.

This is however not very convenient, because if there is a multithreaded
server with each request mapped to thread, and a handling thread for
only 1 request fails this way, we kill the whole server process.

What could be convenient is to somehow propagate the error to calling
thread, e.g. unwinding the stack in a C++-style exceptions way and
turning that back to python exception at some point. And in the future
we maybe could try to do it.

For now we take a small step forward - we can terminate only the thread
which caused failed loadblk() - i.e. we still kill the code, without
providing it a way to recover, but we kill only the working thread, not
the whole process.

To test the functionality, we leverage our tfault framework which is now
extended to verify not only at which function a testcase dies, but more
generally it now examines the traceback (so that we can track coredump
to which thread terminated), and also it now verifies exit status code
and terminating signal of dying process.

NOTE on Linux it is not easy to terminate only 1 thread and produce a
coredump for debugging and have right process exit status if e.g. main
thread is terminated this way.

The reason is Linux hardcodes termination-with-coredump to kill all
threads from a process, and even separate processes which happen to
share virtual memory layout with the killing thread.

So to do such termination, we use hacks and workarounds - see comments
in newly introduced __abort_thread().

NOTE2 for getting separate coredump files for several faulting threads

    /proc/sys/kernel/core_pattern   or
    /proc/sys/kernel/core_uses_pid

are your friends.

/cc @Tyagov
/cc @klaus

diff --git a/t/tfault-run b/t/tfault-run
--- a/t/tfault-run
+++ b/t/tfault-run
@@ -1,7 +1,10 @@
 #!/bin/sh -e
-# tfault-run <tfault> <arg> <mustdie>
+# tfault-run <tfault> <arg> <mustdie> <signal> [exitcode]
 # run `<tfault> <arg>` and verify that it produces correct coredump, dieing for
-#   SIGSEGV in function <mustdie>.
+#   <signal> with traceback <mustdie>.
+#
+# NOTE mustdie is generally func1,func2,func3,... - traceback tail is checked to be func1<-func2<-func3
+# NOTE if exitcode not present - it is checked to be non-zero
 
 # die <msg> ...
 die() {
@@ -12,6 +15,8 @@ die() {
 tfault=$(realpath $1)
 arg=$2
 mustdie=$3
+signal=$4
+exitcode=$5
 
 # XXX ok to hardcode t/ ?
 workdir=t/tfault-run.$arg
@@ -22,21 +27,38 @@ cd "$workdir"
 
 ulimit -c unlimited
 $tfault $arg 2>&1 |tee run.out
+st="${PIPESTATUS[0]}"
+if test -z "$exitcode"; then
+    test $st != 0                       || die "test exit code is 0"
+else
+    test $st == $exitcode               || die "test exit code unexpected ($st != $exitcode)"
+fi
 
 grep -q "^# going to fault" run.out     || die "test didn't run to faulting point"
 test -e core                            || die "no core after run"
-gdb -q -batch $tfault core >core.info   || die "can't gdb(core)"
-grep -q "Program terminated with signal SIGSEGV, Segmentation fault." core.info || die "not SIGSEGV"
+gdb -q -batch $tfault core >core.info   || die "can't gdb-info(core)"
+grep -q "Program terminated with signal $signal" core.info || die "not $signal"
+gdb -batch-silent   \
+    -ex "set logging file /dev/stdout"  \
+    -ex "set logging on"    \
+    -ex bt $tfault core >core.bt        || die "can't gdb-bt(core)"
 
-# #0  0x00000000004031ae in doublefault_loadblk (file=0x7fff0f25d9c0, blk=0, buf=0x7ff85a553000) at t/tfault.c:93
-diefunc=$(grep '^#0' core.info | awk '{print $4}')
-test -n "$diefunc" || die "can't extract diefunc"
+# verify mustdie
+mustdie_depth=`echo $mustdie | sed 's/,/ /g' | wc -w`
+diebt=
+for nframe in `seq 0 $(($mustdie_depth - 1))`; do
+    # #0  0x00000000004031ae in doublefault_loadblk (file=0x7fff0f25d9c0, blk=0, buf=0x7ff85a553000) at t/tfault.c:93
+    # #5  <signal handler called>
+    framefunc=$(grep "^#$nframe" core.bt | awk '{print $4}')
+    test "$framefunc" = "called>" && framefunc=sighandler   # <signal handler called> -> sighandler
+    diebt=$diebt${diebt:+,}$framefunc
+done
 
-test "$diefunc" == "$mustdie"   || die "must die in $mustdie, died in $diefunc"
+test "$diebt" == "$mustdie"   || die "must die via $mustdie, died via $diebt"
 
 
 # run ok - cleanup
 cd "$cwd"
 rm -rf "$workdir"
 
-echo "ok   - crashed OK  (in $diefunc)"
+echo "ok   - crashed OK  (via $diebt)"
